### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by vahid45** [Couchiman/CRMSSIS#17]
When i installed your component in ssis toolbox nothing appeared

**Comment by Couchiman** [comment]
Hi, did you run the scripts for registration? Which SQL version do you have? 
Check "Fast deploy example for SQL Server 2016" section on Wiki

**Comment by vahid45** [comment]
my sql is 2016 but i did not use fast script .i manually copy dll to sql direction and copy to gac

**Comment by vahid45** [comment]
do you can create setup file for your project? ;)

**Comment by Couchiman** [comment]
Hi vahid45, i created and installer but still have to test it. i have already uploaded it but i still need to make a clean install on my machine

**Comment by Couchiman** [comment]
Done. Check the release section or https://github.com/Couchiman/CRMSSIS/releases/download/1.0b/SQL2016x64b.msi

**Comment by vahid45** [comment]
very good job Couchiman.I have very good idea about ssis component for dynamics crm if you want i can tell it to you for improving your project

**Comment by vahid45** [comment]
> Done. Check the release section or https://github.com/Couchiman/CRMSSIS/releases/download/1.0b/SQL2016x64b.msi

Not Working For me again. My Sql is 2016 but my ssdt is visual studio 2015.

**Comment by Couchiman** [comment]
Remove all dll's that you copy manually, then reinstall using the msi package.
Some ssdt versions have some problems in my machine, im using 15.1.61808. Check the about box on visual studio.

**Comment by Couchiman** [comment]
> Remove all dll's that you copy manually, then reinstall using the msi package.
> Some ssdt versions have some problems in my machine, im using 15.1.61808 for vs 2017. Check the about box on visual studio
For vs 2015 im using 14.0.61021

**Comment by Couchiman** [comment]
Here you have two more techniques:
http://ryangaraygay.com/adding-custom-ssis-transformation-to-visual-studio-toolbox-fails/
https://jessekraut.wordpress.com/ssis-2012-custom-component-install-guidelines/ --> Your sql folder will be 130 for sql server 2016

**Comment by vahid45** [comment]
i installed in fresh machine with vs 15 that`s worked.thank you for help
